import type { SeedChapter } from "./types.ts";

/**
 * Class 8 · Solving Linear Equations · slice 1.5
 *
 * ⚠️ EDITION NOTE (D1). This is the one chapter where the two editions genuinely
 * differ. Old NCERT has a dedicated "Linear Equations in One Variable" chapter;
 * Ganita Prakash **dissolved it** into the broader "Algebra Play" chapter. The
 * skills are identical and still examined — only the packaging moved — so
 * `ncert_ref` cites both and a learner on either book recognises the content.
 *
 * NCERT teaching order:
 *   what an equation is → variable on one side → brackets and fractions
 *   → variable on both sides → forming equations from words
 *
 * Answers are the VALUE of x (`integer` or `fraction`), never the string "x=4".
 * Two reasons: it is how NCERT asks, and it keeps this chapter off the
 * `expression` grading path, which is the least predictable one.
 */
export const class8LinearEquations: SeedChapter = {
  slug: "class8-linear-equations",
  grade: 8,
  number: 2,
  title: "Solving Linear Equations",
  summary:
    "What an equation really says, how to solve it step by step, and how to turn a word problem into one.",
  ncert_ref:
    "Ganita Prakash Class 8 Part 2 Ch 6 (Algebra Play — no dedicated chapter) · old NCERT Class 8 Ch 2 (Linear Equations in One Variable)",
  order_index: 1,

  concepts: [
    { slug: "linear-equation-basics", name: "What an Equation Is", order_index: 1 },
    { slug: "solving-one-side", name: "Solving Step by Step", order_index: 2 },
    { slug: "variable-both-sides", name: "The Variable on Both Sides", order_index: 3 },
    { slug: "equation-word-problems", name: "Turning Words into Equations", order_index: 4 },
  ],

  lessons: [
    {
      slug: "c8-linear-l1",
      concept_slug: "linear-equation-basics",
      order_index: 1,
      title: "What an Equation Really Says",
      est_minutes: 4,
      body_md: [
        "You buy 3 pens and a ₹5 eraser, and the shopkeeper asks for ₹35. What does one pen cost?",
        "",
        "You already know how to nag at this until it gives way. Algebra just writes it down neatly:",
        "",
        "$$",
        "3x + 5 = 35",
        "$$",
        "",
        "### The three words",
        "",
        "- The **variable** is $x$ — the thing you do not know yet.",
        "- An **equation** says two things are equal. The $=$ sign is a claim, not an instruction.",
        "- A **solution** is a value of the variable that makes the claim true.",
        "",
        "> An equation is a balance. Whatever is on the left weighs exactly the same as whatever is on the right.",
        "",
        "### Linear, in one variable",
        "",
        "This chapter is about equations where the variable appears **on its own** — no $x^2$, no $\\sqrt{x}$, and only one letter.",
        "",
        "$$",
        "2x + 5 = 11 \\quad \\checkmark \\qquad x^2 + 3 = 7 \\quad \\times",
        "$$",
        "",
        "### Checking beats guessing",
        "",
        "The best habit in this whole chapter: **put your answer back in**. If both sides come out the same, you are right — you never have to wonder.",
        "",
        "### Worked example",
        "",
        "Is $x = 3$ a solution of $4x - 2 = 10$?",
        "",
        "Put 3 in place of $x$ on the left:",
        "",
        "$$",
        "4 \\times 3 - 2 = 12 - 2 = 10",
        "$$",
        "",
        "The right side is also 10. Both sides match, so **yes**, $x = 3$ is the solution.",
      ].join("\n"),
    },
    {
      slug: "c8-linear-l2",
      concept_slug: "solving-one-side",
      order_index: 2,
      title: "Solving Step by Step",
      est_minutes: 5,
      body_md: [
        "Solving means getting the variable **alone** on one side. You do it by undoing what has been done to it.",
        "",
        "> Whatever you do to one side, do to the other. The balance must stay level.",
        "",
        "### Undo in reverse order",
        "",
        "Take $2x + 5 = 17$. The $x$ has been multiplied by 2, *then* had 5 added. So undo the adding first, then the multiplying.",
        "",
        "$$",
        "2x + 5 = 17",
        "$$",
        "",
        "Subtract 5 from **both** sides:",
        "",
        "$$",
        "2x = 12",
        "$$",
        "",
        "Divide **both** sides by 2:",
        "",
        "$$",
        "x = 6",
        "$$",
        "",
        "Check: $2 \\times 6 + 5 = 17 \\ \\checkmark$",
        "",
        "### The shortcut, and what it really is",
        "",
        "People say \"take it to the other side and change the sign\". That is not a separate rule — it is what subtracting from both sides *looks like* once you stop writing the middle step.",
        "",
        "$$",
        "3x + 4 = 19 \\quad \\Rightarrow \\quad 3x = 19 - 4",
        "$$",
        "",
        "Use the shortcut if you like, but if an answer ever looks wrong, write the middle step back in. That is where the mistake will be.",
        "",
        "### Worked example",
        "",
        "Solve $5x - 8 = 27$.",
        "",
        "$$",
        "5x = 27 + 8 = 35",
        "$$",
        "",
        "$$",
        "x = 35 \\div 5 = 7",
        "$$",
        "",
        "Check: $5 \\times 7 - 8 = 35 - 8 = 27 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-linear-l3",
      concept_slug: "solving-one-side",
      order_index: 3,
      title: "Brackets and Fractions",
      est_minutes: 4,
      body_md: [
        "Two things make an equation *look* harder than it is. Neither changes the method.",
        "",
        "### Brackets — open them first",
        "",
        "$$",
        "3(x + 2) = 21",
        "$$",
        "",
        "The 3 multiplies **everything** inside, not just the $x$:",
        "",
        "$$",
        "3x + 6 = 21",
        "$$",
        "",
        "$$",
        "3x = 15, \\qquad x = 5",
        "$$",
        "",
        "Forgetting to multiply the second term is the most common slip here. $3(x+2)$ is $3x + 6$, never $3x + 2$.",
        "",
        "### Fractions — the variable is still just a number",
        "",
        "$$",
        "\\frac{x}{4} = 3",
        "$$",
        "",
        "$x$ has been divided by 4, so undo it by multiplying both sides by 4:",
        "",
        "$$",
        "x = 12",
        "$$",
        "",
        "### When the answer is not a whole number",
        "",
        "That is completely normal — do not assume you have gone wrong.",
        "",
        "$$",
        "4x + 3 = 10",
        "$$",
        "",
        "$$",
        "4x = 7, \\qquad x = \\frac{7}{4}",
        "$$",
        "",
        "Leave it as $\\frac{7}{4}$. A fraction is an exact answer; a rounded decimal is not.",
        "",
        "### Worked example",
        "",
        "Solve $\\frac{x}{3} + 4 = 9$.",
        "",
        "Subtract 4 from both sides:",
        "",
        "$$",
        "\\frac{x}{3} = 5",
        "$$",
        "",
        "Multiply both sides by 3:",
        "",
        "$$",
        "x = 15",
        "$$",
        "",
        "Check: $15 \\div 3 + 4 = 5 + 4 = 9 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-linear-l4",
      concept_slug: "variable-both-sides",
      order_index: 4,
      title: "The Variable on Both Sides",
      est_minutes: 4,
      body_md: [
        "Sometimes the unknown turns up on both sides:",
        "",
        "$$",
        "7x - 2 = 5x + 10",
        "$$",
        "",
        "Nothing new is needed. **Gather the variable on one side and the plain numbers on the other**, then finish as before.",
        "",
        "### Step by step",
        "",
        "Take $5x$ from both sides, so the right side has no $x$ left:",
        "",
        "$$",
        "2x - 2 = 10",
        "$$",
        "",
        "Add 2 to both sides:",
        "",
        "$$",
        "2x = 12",
        "$$",
        "",
        "Divide both sides by 2:",
        "",
        "$$",
        "x = 6",
        "$$",
        "",
        "Check both sides separately — this is where checking earns its keep:",
        "",
        "$$",
        "7 \\times 6 - 2 = 40 \\qquad 5 \\times 6 + 10 = 40 \\quad \\checkmark",
        "$$",
        "",
        "### Which side should the variable go to?",
        "",
        "Either works. Moving the **smaller** number of $x$s keeps things positive and is usually less fiddly.",
        "",
        "### The mistake to watch for",
        "",
        "> Moving a term across the $=$ sign **changes its sign**. Every time.",
        "",
        "In $3x + 4 = x + 10$, moving the 4 across makes it $-4$:",
        "",
        "$$",
        "3x - x = 10 - 4",
        "$$",
        "",
        "$$",
        "2x = 6, \\qquad x = 3",
        "$$",
        "",
        "If you carry the 4 across as $+4$ you get $x = 7$, and the check fails immediately — which is exactly what checking is for.",
      ].join("\n"),
    },
    {
      slug: "c8-linear-l5",
      concept_slug: "equation-word-problems",
      order_index: 5,
      title: "Turning Words into Equations",
      est_minutes: 5,
      body_md: [
        "This is the part that matters outside the exam hall, and the part most learners find hardest — not the algebra, but knowing what to write down.",
        "",
        "### Three steps, every time",
        "",
        "1. **Name the unknown.** Let $x$ be the thing the question asks for.",
        "2. **Say the same sentence in symbols.**",
        "3. **Solve, then read the answer back into the question.**",
        "",
        "### The phrases, translated",
        "",
        "| In words | In symbols |",
        "|---|---|",
        "| a number increased by 8 | $x + 8$ |",
        "| 5 less than a number | $x - 5$ |",
        "| three times a number | $3x$ |",
        "| twice a number, then add 7 | $2x + 7$ |",
        "| ₹15 more than the pen | $x + 15$ |",
        "",
        "Watch \"5 less than a number\" — it is $x - 5$, not $5 - x$. The order in English is the reverse of the order in symbols.",
        "",
        "### Worked example",
        "",
        "A pen costs ₹$x$. A notebook costs ₹15 more than the pen. Together they cost ₹85. What does the pen cost?",
        "",
        "The notebook is $x + 15$, so together:",
        "",
        "$$",
        "x + (x + 15) = 85",
        "$$",
        "",
        "$$",
        "2x + 15 = 85",
        "$$",
        "",
        "$$",
        "2x = 70, \\qquad x = 35",
        "$$",
        "",
        "The pen costs **₹35**. Read it back: the notebook is ₹50, and $35 + 50 = 85 \\ \\checkmark$",
        "",
        "That last line is not optional. An answer that solves the equation but not the question is the commonest way to lose marks here.",
      ].join("\n"),
    },
  ],

  questions: [
    // ── linear-equation-basics ──────────────────────────────────────────────
    {
      slug: "c8-basics-d1-q1",
      concept_slug: "linear-equation-basics",
      kind: "practice",
      difficulty: 1,
      answer_type: "mcq",
      stem_md: "Which of these is a **linear equation in one variable**?",
      choices: [
        { id: "a", label: "$2x + 5 = 11$" },
        { id: "b", label: "$x^2 + 3 = 7$" },
        { id: "c", label: "$3x + 2y = 6$" },
        { id: "d", label: "$5 + 7 = 12$" },
      ],
      answer_value: "a",
      solution_md: [
        "Three things have to be true: there is an $=$ sign, there is exactly **one** letter, and that letter is **not** raised to a power.",
        "",
        "- (a) $2x + 5 = 11$ — one variable, power 1. **Yes.**",
        "- (b) has $x^2$, so it is not linear.",
        "- (c) has two variables, $x$ and $y$.",
        "- (d) has no variable at all — it is just a true statement.",
      ].join("\n"),
    },
    {
      slug: "c8-basics-d1-q2",
      concept_slug: "linear-equation-basics",
      kind: "practice",
      difficulty: 1,
      answer_type: "mcq",
      stem_md: "Is $x = 3$ a solution of $4x - 2 = 10$?",
      choices: [
        { id: "a", label: "Yes — both sides come out as 10" },
        { id: "b", label: "No — the left side comes out as 14" },
        { id: "c", label: "No — $x$ should be 4" },
        { id: "d", label: "You cannot tell without solving it first" },
      ],
      answer_value: "a",
      solution_md: [
        "Put 3 in place of $x$ and work out the left side:",
        "",
        "$$",
        "4 \\times 3 - 2 = 12 - 2 = 10",
        "$$",
        "",
        "The right side is 10 too, so the two sides balance and $x = 3$ is the solution.",
        "",
        "Option (d) is worth ruling out: checking is *faster* than solving, and it always works.",
      ].join("\n"),
    },
    {
      slug: "c8-basics-d2-q1",
      concept_slug: "linear-equation-basics",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\nx + 7 = 12\n$$\n\nWhat is the value of $x$?",
      answer_value: "5",
      solution_md: [
        "7 has been added to $x$, so undo it by subtracting 7 from **both** sides:",
        "",
        "$$",
        "x = 12 - 7 = 5",
        "$$",
        "",
        "Check: $5 + 7 = 12 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-basics-d2-q2",
      concept_slug: "linear-equation-basics",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "If $x = -2$, what is the value of $3x + 8$?",
      answer_value: "2",
      solution_md: [
        "Put $-2$ in place of $x$:",
        "",
        "$$",
        "3 \\times (-2) + 8 = -6 + 8 = 2",
        "$$",
        "",
        "The sign rules from Class 7 still apply — a negative times a positive is negative.",
      ].join("\n"),
    },
    {
      slug: "c8-basics-d3-q1",
      concept_slug: "linear-equation-basics",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md:
        "For which value of $x$ do both sides of $2x + 1 = x + 6$ come out equal?",
      answer_value: "5",
      solution_md: [
        "Gather the $x$ terms on the left and the numbers on the right:",
        "",
        "$$",
        "2x - x = 6 - 1",
        "$$",
        "",
        "$$",
        "x = 5",
        "$$",
        "",
        "Check both sides separately: $2 \\times 5 + 1 = 11$ and $5 + 6 = 11 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-basics-d3-q2",
      concept_slug: "linear-equation-basics",
      kind: "practice",
      difficulty: 3,
      answer_type: "mcq",
      stem_md: "Sunita says $x = 4$ solves $5x - 3 = 17$.\n\nIs she right?",
      choices: [
        { id: "a", label: "Yes — both sides come out as 17" },
        { id: "b", label: "No — the left side comes out as 20" }, // forgot the -3
        { id: "c", label: "No — $x$ should be 5" },
        { id: "d", label: "You cannot check without solving it again" },
      ],
      answer_value: "a",
      solution_md: [
        "Substitute and see:",
        "",
        "$$",
        "5 \\times 4 - 3 = 20 - 3 = 17",
        "$$",
        "",
        "That matches the right side, so Sunita is right.",
        "",
        "Option (b) is what you get by forgetting the $-3$ — worth noticing, because it is the easiest step to skip when checking quickly.",
      ].join("\n"),
    },

    // ── solving-one-side ────────────────────────────────────────────────────
    {
      slug: "c8-one-d1-q1",
      concept_slug: "solving-one-side",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n3x = 21\n$$\n\nWhat is the value of $x$?",
      answer_value: "7",
      solution_md: [
        "$x$ has been multiplied by 3, so divide **both** sides by 3:",
        "",
        "$$",
        "x = 21 \\div 3 = 7",
        "$$",
        "",
        "Check: $3 \\times 7 = 21 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-one-d1-q2",
      concept_slug: "solving-one-side",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\nx - 9 = 4\n$$\n\nWhat is the value of $x$?",
      answer_value: "13",
      solution_md: [
        "9 has been taken away from $x$, so add 9 to both sides:",
        "",
        "$$",
        "x = 4 + 9 = 13",
        "$$",
        "",
        "Check: $13 - 9 = 4 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-one-d2-q1",
      concept_slug: "solving-one-side",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n2x + 5 = 17\n$$\n\nWhat is the value of $x$?",
      answer_value: "6",
      solution_md: [
        "Undo the adding first, then the multiplying.",
        "",
        "$$",
        "2x = 17 - 5 = 12",
        "$$",
        "",
        "$$",
        "x = 12 \\div 2 = 6",
        "$$",
        "",
        "Check: $2 \\times 6 + 5 = 17 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-one-d2-q2",
      concept_slug: "solving-one-side",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n5x - 8 = 27\n$$\n\nWhat is the value of $x$?",
      answer_value: "7",
      solution_md: [
        "Add 8 to both sides, then divide by 5.",
        "",
        "$$",
        "5x = 27 + 8 = 35",
        "$$",
        "",
        "$$",
        "x = 35 \\div 5 = 7",
        "$$",
        "",
        "Check: $5 \\times 7 - 8 = 27 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-one-d3-q1",
      concept_slug: "solving-one-side",
      kind: "practice",
      difficulty: 3,
      answer_type: "fraction",
      stem_md: "$$\n4x + 3 = 10\n$$\n\nWhat is the value of $x$?",
      answer_value: "7/4",
      solution_md: [
        "Subtract 3 from both sides:",
        "",
        "$$",
        "4x = 7",
        "$$",
        "",
        "Divide both sides by 4:",
        "",
        "$$",
        "x = \\frac{7}{4}",
        "$$",
        "",
        "Not every answer is a whole number, and that is fine. Leave it as a fraction — it is exact.",
      ].join("\n"),
    },
    {
      slug: "c8-one-d3-q2",
      concept_slug: "solving-one-side",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: "$$\n\\frac{x}{3} + 4 = 9\n$$\n\nWhat is the value of $x$?",
      answer_value: "15",
      solution_md: [
        "Subtract 4 from both sides first:",
        "",
        "$$",
        "\\frac{x}{3} = 5",
        "$$",
        "",
        "$x$ has been divided by 3, so multiply both sides by 3:",
        "",
        "$$",
        "x = 15",
        "$$",
        "",
        "Check: $15 \\div 3 + 4 = 9 \\ \\checkmark$",
      ].join("\n"),
    },

    // ── variable-both-sides ─────────────────────────────────────────────────
    {
      slug: "c8-both-d1-q1",
      concept_slug: "variable-both-sides",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n5x = 3x + 8\n$$\n\nWhat is the value of $x$?",
      answer_value: "4",
      solution_md: [
        "Take $3x$ from both sides so the $x$s are all on the left:",
        "",
        "$$",
        "2x = 8",
        "$$",
        "",
        "$$",
        "x = 4",
        "$$",
        "",
        "Check: $5 \\times 4 = 20$ and $3 \\times 4 + 8 = 20 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-both-d1-q2",
      concept_slug: "variable-both-sides",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n7x - 2 = 5x + 10\n$$\n\nWhat is the value of $x$?",
      answer_value: "6",
      solution_md: [
        "Gather the $x$s on the left and the numbers on the right:",
        "",
        "$$",
        "7x - 5x = 10 + 2",
        "$$",
        "",
        "$$",
        "2x = 12, \\qquad x = 6",
        "$$",
        "",
        "Check: $7 \\times 6 - 2 = 40$ and $5 \\times 6 + 10 = 40 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-both-d2-q1",
      concept_slug: "variable-both-sides",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n4x + 9 = 7x - 6\n$$\n\nWhat is the value of $x$?",
      answer_value: "5",
      solution_md: [
        "Here the right side has more $x$s, so move the $x$s there and the numbers to the left — it keeps everything positive.",
        "",
        "$$",
        "9 + 6 = 7x - 4x",
        "$$",
        "",
        "$$",
        "15 = 3x, \\qquad x = 5",
        "$$",
        "",
        "Check: $4 \\times 5 + 9 = 29$ and $7 \\times 5 - 6 = 29 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-both-d2-q2",
      concept_slug: "variable-both-sides",
      kind: "practice",
      difficulty: 2,
      answer_type: "mcq",
      stem_md: [
        "Rohit solved $3x + 4 = x + 10$ and got $x = 7$.",
        "",
        "What went wrong?",
      ].join("\n"),
      choices: [
        { id: "a", label: "He moved the 4 across without changing its sign" },
        { id: "b", label: "Nothing — $x = 7$ is correct" },
        { id: "c", label: "He should have divided by 3 first" },
        { id: "d", label: "He should have got $x = 14$" },
      ],
      answer_value: "a",
      solution_md: [
        "Done properly:",
        "",
        "$$",
        "3x - x = 10 - 4",
        "$$",
        "",
        "$$",
        "2x = 6, \\qquad x = 3",
        "$$",
        "",
        "Rohit carried the 4 across as $+4$ instead of $-4$, giving $2x = 14$ and $x = 7$.",
        "",
        "**A term that crosses the $=$ sign changes its sign.** Checking would have caught it at once: $3 \\times 7 + 4 = 25$, but $7 + 10 = 17$.",
      ].join("\n"),
    },
    {
      slug: "c8-both-d3-q1",
      concept_slug: "variable-both-sides",
      kind: "practice",
      difficulty: 3,
      answer_type: "fraction",
      stem_md: "$$\n6x - 1 = 2x + 4\n$$\n\nWhat is the value of $x$?",
      answer_value: "5/4",
      solution_md: [
        "Gather the $x$s left, the numbers right:",
        "",
        "$$",
        "6x - 2x = 4 + 1",
        "$$",
        "",
        "$$",
        "4x = 5, \\qquad x = \\frac{5}{4}",
        "$$",
        "",
        "A fraction answer is not a sign that something went wrong. Leave it exact.",
      ].join("\n"),
    },
    {
      slug: "c8-both-d3-q2",
      concept_slug: "variable-both-sides",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: "$$\n2(x + 3) = x + 11\n$$\n\nWhat is the value of $x$?",
      answer_value: "5",
      solution_md: [
        "Open the bracket first — the 2 multiplies **both** terms inside:",
        "",
        "$$",
        "2x + 6 = x + 11",
        "$$",
        "",
        "$$",
        "2x - x = 11 - 6",
        "$$",
        "",
        "$$",
        "x = 5",
        "$$",
        "",
        "Check: $2 \\times (5 + 3) = 16$ and $5 + 11 = 16 \\ \\checkmark$",
      ].join("\n"),
    },

    // ── equation-word-problems ──────────────────────────────────────────────
    {
      slug: "c8-word-d1-q1",
      concept_slug: "equation-word-problems",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "A number increased by 8 gives 23.\n\nWhat is the number?",
      answer_value: "15",
      solution_md: [
        "Let the number be $x$. *Increased by 8* means $x + 8$:",
        "",
        "$$",
        "x + 8 = 23",
        "$$",
        "",
        "$$",
        "x = 23 - 8 = 15",
        "$$",
        "",
        "Read it back: 15 increased by 8 is 23 $\\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-word-d1-q2",
      concept_slug: "equation-word-problems",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "Three times a number is 27.\n\nWhat is the number?",
      answer_value: "9",
      solution_md: [
        "Let the number be $x$. *Three times a number* is $3x$:",
        "",
        "$$",
        "3x = 27, \\qquad x = 9",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c8-word-d2-q1",
      concept_slug: "equation-word-problems",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: [
        "A pen costs ₹$x$. A notebook costs ₹15 more than the pen.",
        "",
        "Together they cost ₹85. What does the **pen** cost, in rupees?",
      ].join("\n"),
      answer_value: "35",
      solution_md: [
        "The notebook is $x + 15$, so together:",
        "",
        "$$",
        "x + (x + 15) = 85",
        "$$",
        "",
        "$$",
        "2x + 15 = 85",
        "$$",
        "",
        "$$",
        "2x = 70, \\qquad x = 35",
        "$$",
        "",
        "The pen is ₹35 and the notebook ₹50. Read it back: $35 + 50 = 85 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-word-d2-q2",
      concept_slug: "equation-word-problems",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: [
        "Meena's age plus 5 is the same as twice her age minus 3.",
        "",
        "How old is Meena?",
      ].join("\n"),
      answer_value: "8",
      solution_md: [
        "Let her age be $x$:",
        "",
        "$$",
        "x + 5 = 2x - 3",
        "$$",
        "",
        "$$",
        "5 + 3 = 2x - x",
        "$$",
        "",
        "$$",
        "x = 8",
        "$$",
        "",
        "Check: $8 + 5 = 13$ and $2 \\times 8 - 3 = 13 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-word-d3-q1",
      concept_slug: "equation-word-problems",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: [
        "A rectangle is 4 cm longer than it is wide. Its perimeter is 40 cm.",
        "",
        "What is its **width**, in cm?",
      ].join("\n"),
      answer_value: "8",
      solution_md: [
        "Let the width be $x$, so the length is $x + 4$.",
        "",
        "Perimeter is twice the width plus twice the length:",
        "",
        "$$",
        "2x + 2(x + 4) = 40",
        "$$",
        "",
        "$$",
        "4x + 8 = 40",
        "$$",
        "",
        "$$",
        "4x = 32, \\qquad x = 8",
        "$$",
        "",
        "Width 8 cm, length 12 cm. Check: $8 + 12 + 8 + 12 = 40 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-word-d3-q2",
      concept_slug: "equation-word-problems",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: [
        "Rahul spends ₹120 and is left with one third of what he started with.",
        "",
        "How much did he start with, in rupees?",
      ].join("\n"),
      answer_value: "180",
      solution_md: [
        "Let him start with $x$. After spending ₹120 he has $x - 120$, and that equals a third of $x$:",
        "",
        "$$",
        "x - 120 = \\frac{x}{3}",
        "$$",
        "",
        "Multiply everything by 3 to clear the fraction:",
        "",
        "$$",
        "3x - 360 = x",
        "$$",
        "",
        "$$",
        "2x = 360, \\qquad x = 180",
        "$$",
        "",
        "Check: he spends ₹120 of ₹180 and has ₹60 left, which is indeed a third of 180 $\\checkmark$",
      ].join("\n"),
    },

    // ── quiz ────────────────────────────────────────────────────────────────
    {
      slug: "c8-quiz-basics-1",
      concept_slug: "linear-equation-basics",
      kind: "quiz",
      difficulty: 1,
      answer_type: "mcq",
      stem_md: "Which of these is a **linear equation in one variable**?",
      choices: [
        { id: "a", label: "$3y - 7 = 8$" },
        { id: "b", label: "$y^2 = 9$" },
        { id: "c", label: "$2a + 3b = 7$" },
        { id: "d", label: "$4 + 5 = 9$" },
      ],
      answer_value: "a",
      solution_md: [
        "One letter, power 1, and an $=$ sign. Only $3y - 7 = 8$ has all three.",
        "",
        "The letter does not have to be $x$ — $y$, $a$ or any other letter works the same way.",
      ].join("\n"),
    },
    {
      slug: "c8-quiz-basics-2",
      concept_slug: "linear-equation-basics",
      kind: "quiz",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "If $x = 5$, what is the value of $4x - 9$?",
      answer_value: "11",
      solution_md: [
        "$$",
        "4 \\times 5 - 9 = 20 - 9 = 11",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c8-quiz-one-1",
      concept_slug: "solving-one-side",
      kind: "quiz",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n6x + 7 = 43\n$$\n\nWhat is the value of $x$?",
      answer_value: "6",
      solution_md: [
        "$$",
        "6x = 43 - 7 = 36",
        "$$",
        "",
        "$$",
        "x = 36 \\div 6 = 6",
        "$$",
        "",
        "Check: $6 \\times 6 + 7 = 43 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-quiz-one-2",
      concept_slug: "solving-one-side",
      kind: "quiz",
      difficulty: 3,
      answer_type: "fraction",
      stem_md: "$$\n2x + 9 = 14\n$$\n\nWhat is the value of $x$?",
      answer_value: "5/2",
      solution_md: [
        "$$",
        "2x = 14 - 9 = 5",
        "$$",
        "",
        "$$",
        "x = \\frac{5}{2}",
        "$$",
        "",
        "Leave it as a fraction — it is the exact answer.",
      ].join("\n"),
    },
    {
      slug: "c8-quiz-both-1",
      concept_slug: "variable-both-sides",
      kind: "quiz",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n9x - 4 = 6x + 11\n$$\n\nWhat is the value of $x$?",
      answer_value: "5",
      solution_md: [
        "$$",
        "9x - 6x = 11 + 4",
        "$$",
        "",
        "$$",
        "3x = 15, \\qquad x = 5",
        "$$",
        "",
        "Check: $9 \\times 5 - 4 = 41$ and $6 \\times 5 + 11 = 41 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-quiz-both-2",
      concept_slug: "variable-both-sides",
      kind: "quiz",
      difficulty: 3,
      answer_type: "integer",
      stem_md: "$$\n3(x - 2) = x + 6\n$$\n\nWhat is the value of $x$?",
      answer_value: "6",
      solution_md: [
        "Open the bracket first — the 3 multiplies both terms:",
        "",
        "$$",
        "3x - 6 = x + 6",
        "$$",
        "",
        "$$",
        "2x = 12, \\qquad x = 6",
        "$$",
        "",
        "Check: $3 \\times (6 - 2) = 12$ and $6 + 6 = 12 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c8-quiz-word-1",
      concept_slug: "equation-word-problems",
      kind: "quiz",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "A number is doubled and then increased by 7, giving 31.\n\nWhat is the number?",
      answer_value: "12",
      solution_md: [
        "Let the number be $x$:",
        "",
        "$$",
        "2x + 7 = 31",
        "$$",
        "",
        "$$",
        "2x = 24, \\qquad x = 12",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c8-quiz-word-2",
      concept_slug: "equation-word-problems",
      kind: "quiz",
      difficulty: 3,
      answer_type: "integer",
      stem_md:
        "The sum of three consecutive integers is 48.\n\nWhat is the **smallest** of them?",
      answer_value: "15",
      solution_md: [
        "Let the smallest be $x$. The next two are $x + 1$ and $x + 2$:",
        "",
        "$$",
        "x + (x + 1) + (x + 2) = 48",
        "$$",
        "",
        "$$",
        "3x + 3 = 48",
        "$$",
        "",
        "$$",
        "3x = 45, \\qquad x = 15",
        "$$",
        "",
        "The three integers are 15, 16 and 17. Check: $15 + 16 + 17 = 48 \\ \\checkmark$",
      ].join("\n"),
    },
  ],
};
