import type { SeedChapter } from "./types.ts";

/**
 * Class 7 · Integers · slice 1.5
 *
 * NCERT teaching order (stable across editions — the numbering is not, D1):
 *
 *   integers and the number line → addition → subtraction (adding the opposite)
 *   → multiplication and its sign rules → division and its sign rules
 *
 * The sign rules are the whole chapter. Every misconception here is a sign
 * error, so the distractors are built from real ones: "−2 is smaller than −5
 * because 2 is smaller than 5", subtracting a negative as if it were positive,
 * and losing a minus when multiplying an odd number of negatives.
 *
 * Display maths uses fenced `$$` on its own lines — `$$x$$` on one line is parsed
 * as INLINE maths by remark-math (found the hard way in slice 1.4).
 */
export const class7Integers: SeedChapter = {
  slug: "class7-integers",
  grade: 7,
  number: 1,
  title: "Integers",
  summary:
    "Negative numbers on the number line, and how to add, subtract, multiply and divide them without losing a sign.",
  ncert_ref:
    "Ganita Prakash Class 7 Part 2 Ch 2 (Operations with Integers) · old NCERT Class 7 Ch 1 (Integers)",
  order_index: 1,

  concepts: [
    { slug: "integers-number-line", name: "Integers and the Number Line", order_index: 1 },
    { slug: "adding-subtracting-integers", name: "Adding and Subtracting Integers", order_index: 2 },
    { slug: "multiplying-integers", name: "Multiplying Integers", order_index: 3 },
    { slug: "dividing-integers", name: "Dividing Integers", order_index: 4 },
  ],

  lessons: [
    {
      slug: "c7-integers-l1",
      concept_slug: "integers-number-line",
      order_index: 1,
      title: "Numbers Below Zero",
      est_minutes: 4,
      body_md: [
        "In January the temperature in Shimla drops to 4 degrees **below** zero. A basement is one floor **below** the ground. You owe your friend ₹50 — you have less than nothing of that money.",
        "",
        "Counting numbers cannot say any of this. **Integers** can.",
        "",
        "Integers are the whole numbers together with their negatives:",
        "",
        "$$",
        "\\ldots, -3, -2, -1, 0, 1, 2, 3, \\ldots",
        "$$",
        "",
        "### The number line settles every argument",
        "",
        "```",
        "  -5  -4  -3  -2  -1   0   1   2   3   4   5",
        "---|---|---|---|---|---|---|---|---|---|---|---",
        "```",
        "",
        "> On the number line, a number is **bigger** if it sits further to the **right**.",
        "",
        "That one rule handles everything. $-2$ is to the right of $-5$, so:",
        "",
        "$$",
        "-2 > -5",
        "$$",
        "",
        "This is where almost everybody slips the first time. It looks as though $-5$ should be bigger, because 5 is bigger than 2. But think about money: owing ₹5 leaves you worse off than owing ₹2. The bigger the number after the minus sign, the *smaller* the integer.",
        "",
        "### Opposites",
        "",
        "Every integer has an **opposite** — the same distance from 0, on the other side. The opposite of 7 is $-7$, and the opposite of $-7$ is 7.",
        "",
        "### Worked example",
        "",
        "Which is greater, $-11$ or $-4$?",
        "",
        "Walk right along the line from $-11$: you pass $-10, -9, \\ldots$ and eventually reach $-4$. Since $-4$ is further right,",
        "",
        "$$",
        "-4 > -11",
        "$$",
      ].join("\n"),
      // ═══════════════════════════════════════════════════════════════════════
      // INTERACTIVE (D18). Every step is a number line, deliberately.
      //
      // Fractions had rotis; integers have no object. A negative number is not a
      // quantity you can hold up — it is a POSITION, and the number line is the
      // only place "-2 is bigger than -5" stops sounding absurd. So the line is
      // the concrete thing here, and every step returns to it.
      // ═══════════════════════════════════════════════════════════════════════
      steps: [
        {
          kind: "see",
          md: "In January, Shimla drops to 4 degrees **below** zero.",
          viz: {
            kind: "numberLine", from: -6, to: 6, step: 2,
            marks: [{ at: -4, label: "−4°C" }],
          },
        },
        {
          kind: "see",
          md: "Counting numbers cannot say that. **Integers** can — the whole numbers and their negatives.",
          viz: { kind: "numberLine", from: -5, to: 5, step: 1 },
        },
        {
          // Asked BEFORE the rule is given. Almost everybody picks −5, and being
          // wrong here is what makes the next screen land.
          kind: "tap",
          md: "Which is bigger: $-2$ or $-5$?",
          options: [{ label: "$-2$" }, { label: "$-5$" }],
          answer: 0,
          why: "It looks as though 5 beats 2. On the number line it does not.",
        },
        {
          kind: "see",
          md: "Further **right** on the line means bigger. $-2$ sits to the right of $-5$.",
          viz: {
            kind: "numberLine", from: -6, to: 6, step: 3,
            // NOT `correct` on −2. Green means "you got it right" everywhere else
            // in the product, and −5 is not a mistake — it is simply smaller.
            // Two neutral tones that differ only in hue let the eye tell the
            // marks apart without implying one of them is wrong.
            marks: [{ at: -5, label: "−5" }, { at: -2, label: "−2", tone: "hint" }],
          },
        },
        {
          // Money, because it is the one place a learner already has the right
          // intuition and does not know it.
          kind: "reveal",
          md: "You owe ₹5. Your friend owes ₹2. Who is worse off?",
          answer: "You are. The bigger the number after the minus sign, the **smaller** the integer.",
        },
        {
          kind: "see",
          md: "Every integer has an **opposite** — the same distance from 0, on the other side.",
          viz: {
            kind: "numberLine", from: -8, to: 8, step: 4,
            marks: [{ at: -7, label: "−7" }, { at: 7, label: "7", tone: "hint" }],
          },
        },
        {
          kind: "tap",
          md: "What is the opposite of $-7$?",
          options: [{ label: "$7$" }, { label: "$-7$" }, { label: "$0$" }],
          answer: 0,
          why: "Same distance from 0, on the other side of it.",
        },
        {
          kind: "reveal",
          md: "Which is greater, $-11$ or $-4$?",
          answer: "$-4$. Walk right from $-11$ and you reach it, so it is further right.",
          viz: {
            kind: "numberLine", from: -12, to: 0, step: 4,
            marks: [{ at: -11, label: "−11" }, { at: -4, label: "−4", tone: "hint" }],
          },
        },
      ],
    },
    {
      slug: "c7-integers-l2",
      concept_slug: "adding-subtracting-integers",
      order_index: 2,
      title: "Adding Integers",
      est_minutes: 4,
      body_md: [
        "Adding an integer is **moving along the number line**. Positive moves right, negative moves left. That is the whole idea.",
        "",
        "### Same signs — add and keep the sign",
        "",
        "Two moves in the same direction just add up.",
        "",
        "$$",
        "(-4) + (-3) = -7",
        "$$",
        "",
        "Owe ₹4, then owe ₹3 more: you owe ₹7.",
        "",
        "### Different signs — subtract, and take the sign of the bigger one",
        "",
        "Now the moves fight each other, and the stronger one wins.",
        "",
        "$$",
        "(-9) + 5 = -4",
        "$$",
        "",
        "Start at $-9$, move 5 to the right, and you land on $-4$. You owed ₹9 and paid back ₹5, so you still owe ₹4.",
        "",
        "$$",
        "(-3) + 8 = 5",
        "$$",
        "",
        "### The pair that makes zero",
        "",
        "> A number plus its opposite is always 0.",
        "",
        "$$",
        "(-6) + 6 = 0",
        "$$",
        "",
        "This is worth remembering, because it is the trick behind solving almost everything later.",
        "",
        "### Worked example",
        "",
        "At 6am the temperature in Leh was $-7$°C. By noon it had risen by 11 degrees.",
        "",
        "Start at $-7$ and move 11 to the right:",
        "",
        "$$",
        "(-7) + 11 = 4",
        "$$",
        "",
        "So it was 4°C at noon.",
      ].join("\n"),
      // Adding is a WALK, so the line carries it — except for the zero pair,
      // which is the one idea a line cannot show. Two chips cancelling can.
      steps: [
        {
          kind: "see",
          md: "Adding is moving along the line. Positive moves right, negative moves left.",
          viz: { kind: "numberLine", from: -10, to: 10, step: 5 },
        },
        {
          kind: "see",
          md: "Two moves the same way just add up. Owe ₹4, then owe ₹3 more.",
          viz: {
            kind: "numberLine", from: -10, to: 2, step: 3,
            jumps: [{ from: 0, to: -4, label: "−4" }, { from: -4, to: -7, label: "−3", tone: "hint" }],
          },
        },
        {
          kind: "reveal",
          md: "So what is $(-4) + (-3)$?",
          answer: "$-7$. Two moves left, and seven steps left altogether.",
        },
        {
          kind: "see",
          md: "Different signs fight each other, and the stronger move wins.",
          viz: {
            kind: "numberLine", from: -10, to: 4, step: 2,
            jumps: [{ from: -9, to: -4, label: "+5" }],
          },
        },
        {
          kind: "tap",
          md: "$(-9) + 5$ lands where?",
          options: [{ label: "$-4$" }, { label: "$-14$" }, { label: "$4$" }],
          answer: 0,
          why: "Start at $-9$ and move 5 right. You owed ₹9 and paid ₹5 back.",
        },
        {
          // The one moment counters beat the line: a pair vanishing IS the idea.
          kind: "see",
          md: "A number plus its opposite is always 0.",
          viz: { kind: "tokenRow", positive: 6, negative: 6, pairing: true, label: "6 + (−6) = 0" },
        },
        {
          kind: "reveal",
          md: "At 6am Leh was $-7$°C. By noon it had risen 11 degrees.",
          answer: "$(-7) + 11 = 4$. So it was 4°C at noon.",
          viz: {
            kind: "numberLine", from: -8, to: 6, step: 2,
            jumps: [{ from: -7, to: 4, label: "+11" }],
          },
        },
        {
          kind: "tap",
          md: "And $(-3) + 8$?",
          options: [{ label: "$5$" }, { label: "$-5$" }, { label: "$11$" }],
          answer: 0,
          why: "Three steps left, then eight right — you end up five right of zero.",
        },
      ],
    },
    {
      slug: "c7-integers-l3",
      concept_slug: "adding-subtracting-integers",
      order_index: 3,
      title: "Subtracting Integers",
      est_minutes: 4,
      body_md: [
        "Subtraction looks like a second thing to learn. It is not — it is addition wearing a different hat.",
        "",
        "> To subtract an integer, **add its opposite**.",
        "",
        "$$",
        "a - b = a + (-b)",
        "$$",
        "",
        "### Subtracting a positive",
        "",
        "$$",
        "5 - 8 = 5 + (-8) = -3",
        "$$",
        "",
        "Start at 5, move 8 to the left, land on $-3$.",
        "",
        "### Subtracting a negative",
        "",
        "This is the one that feels strange, so go slowly.",
        "",
        "$$",
        "(-6) - (-9) = (-6) + 9 = 3",
        "$$",
        "",
        "Taking away a debt makes you **better off**. If someone cancels ₹9 that you owed, you have gained ₹9 — even though the word was *subtract*.",
        "",
        "**Two minus signs next to each other turn into a plus.** Not because of a trick, but because the opposite of $-9$ is $+9$.",
        "",
        "### Worked example",
        "",
        "The temperature in Srinagar fell from $-2$°C to $-11$°C. By how much did it fall?",
        "",
        "$$",
        "(-2) - (-11) = (-2) + 11 = 9",
        "$$",
        "",
        "It fell by 9 degrees. Notice that the answer is positive — a *size* has no minus sign, even when both temperatures do.",
      ].join("\n"),
      // Subtraction is not a second thing to learn, and the lesson refuses to
      // present it as one: every step reduces to the walk from lesson 2.
      steps: [
        {
          kind: "see",
          md: "Subtraction is addition wearing a hat. To subtract, **add the opposite**.",
          viz: { kind: "numberLine", from: -10, to: 10, step: 5 },
        },
        {
          kind: "see",
          md: "$5 - 8$ means start at 5 and move 8 to the left.",
          viz: {
            kind: "numberLine", from: -5, to: 8, step: 3,
            jumps: [{ from: 5, to: -3, label: "−8" }],
          },
        },
        {
          kind: "reveal",
          md: "Where do you land?",
          answer: "On $-3$. So $5 - 8 = 5 + (-8) = -3$.",
        },
        {
          // The strange one, given money first and symbols second.
          kind: "see",
          md: "Now the strange one. If someone cancels ₹9 you owed, you have **gained** ₹9.",
          viz: {
            kind: "numberLine", from: -8, to: 6, step: 2,
            jumps: [{ from: -6, to: 3, label: "+9" }],
          },
        },
        {
          kind: "tap",
          md: "$(-6) - (-9)$ is the same as which one?",
          options: [{ label: "$(-6) + 9$" }, { label: "$(-6) - 9$" }, { label: "$6 + 9$" }],
          answer: 0,
          why: "Subtracting $-9$ means adding its opposite, which is $+9$.",
        },
        {
          kind: "reveal",
          md: "So what is $(-6) - (-9)$?",
          answer: "$3$. Two minus signs together become a plus — because the opposite of $-9$ is $+9$.",
        },
        {
          kind: "see",
          md: "Srinagar fell from $-2$°C to $-11$°C.",
          viz: {
            kind: "numberLine", from: -12, to: 2, step: 2,
            marks: [{ at: -2, label: "−2" }, { at: -11, label: "−11", tone: "hint" }],
          },
        },
        {
          kind: "reveal",
          md: "By how much did it fall?",
          answer: "$(-2) - (-11) = 9$ degrees. A **size** has no minus sign, even when both temperatures do.",
        },
      ],
    },
    {
      slug: "c7-integers-l4",
      concept_slug: "multiplying-integers",
      order_index: 4,
      title: "Multiplying Integers",
      est_minutes: 4,
      body_md: [
        "Multiplication is repeated addition, and that is enough to work out every sign rule for yourself.",
        "",
        "### A negative times a positive",
        "",
        "$$",
        "(-4) \\times 3 = (-4) + (-4) + (-4) = -12",
        "$$",
        "",
        "Three lots of a ₹4 debt is a ₹12 debt.",
        "",
        "### A negative times a negative",
        "",
        "Watch this pattern and let it finish the sentence for you:",
        "",
        "$$",
        "(-4) \\times 2 = -8",
        "$$",
        "",
        "$$",
        "(-4) \\times 1 = -4",
        "$$",
        "",
        "$$",
        "(-4) \\times 0 = 0",
        "$$",
        "",
        "Each time the second number drops by 1, the answer goes **up** by 4. Keep going and the next line has to be $+4$:",
        "",
        "$$",
        "(-4) \\times (-1) = 4",
        "$$",
        "",
        "### The two rules",
        "",
        "> **Same signs give a positive. Different signs give a negative.**",
        "",
        "| The two signs | The answer |",
        "|---|---|",
        "| $(+) \\times (+)$ | positive |",
        "| $(-) \\times (-)$ | positive |",
        "| $(+) \\times (-)$ | negative |",
        "| $(-) \\times (+)$ | negative |",
        "",
        "### More than two numbers",
        "",
        "Count the minus signs. An **even** number of negatives gives a positive; an **odd** number gives a negative.",
        "",
        "### Worked example",
        "",
        "$$",
        "(-2) \\times 3 \\times (-5)",
        "$$",
        "",
        "Two negatives, so the answer is positive. Multiply the sizes: $2 \\times 3 \\times 5 = 30$.",
        "",
        "$$",
        "(-2) \\times 3 \\times (-5) = 30",
        "$$",
      ].join("\n"),
      // Counters, not the line. "Three lots of a debt" is a thing you can count;
      // repeated jumps just look like one long jump.
      steps: [
        {
          kind: "see",
          md: "Multiplying is repeated adding. Here are three lots of a ₹4 debt.",
          viz: { kind: "tokenRow", positive: 0, negative: 12, groupsOf: 4, label: "(−4) × 3" },
        },
        {
          kind: "reveal",
          md: "So what is $(-4) \\times 3$?",
          answer: "$-12$. Three lots of four negatives.",
        },
        {
          // Revealed a line at a time, because the pattern only works if you
          // watch it happen. Shown as a block it is four facts to accept.
          kind: "worked",
          md: "Watch what happens as the second number drops by 1.",
          lines: [
            "$(-4) \\times 2 = -8$",
            "$(-4) \\times 1 = -4$",
            "$(-4) \\times 0 = 0$",
            "Each time, the answer goes **up** by 4.",
          ],
        },
        {
          kind: "reveal",
          md: "So what must $(-4) \\times (-1)$ be?",
          answer: "$4$. The pattern has to keep going up by 4 — nothing else fits.",
        },
        {
          kind: "see",
          md: "That gives the whole rule: **same signs positive, different signs negative**.",
        },
        {
          kind: "tap",
          md: "$(-6) \\times (-7)$?",
          options: [{ label: "$42$" }, { label: "$-42$" }],
          answer: 0,
          why: "Same signs, so the answer is positive. Then $6 \\times 7 = 42$.",
        },
        {
          kind: "see",
          md: "With more than two numbers, count the minus signs. Even is positive, odd is negative.",
        },
        {
          kind: "reveal",
          md: "$(-2) \\times 3 \\times (-5)$?",
          answer: "$30$. Two minus signs is even, so positive. Then $2 \\times 3 \\times 5 = 30$.",
        },
      ],
    },
    {
      slug: "c7-integers-l5",
      concept_slug: "dividing-integers",
      order_index: 5,
      title: "Dividing Integers",
      est_minutes: 3,
      body_md: [
        "Division undoes multiplication, so it borrows the same sign rules — no new ones to learn.",
        "",
        "> **Same signs give a positive. Different signs give a negative.**",
        "",
        "$$",
        "(-24) \\div 6 = -4",
        "$$",
        "",
        "$$",
        "(-36) \\div (-9) = 4",
        "$$",
        "",
        "You can always check a division by multiplying back. Is $(-36) \\div (-9)$ really 4?",
        "",
        "$$",
        "4 \\times (-9) = -36 \\quad \\checkmark",
        "$$",
        "",
        "### One thing division does not share",
        "",
        "Multiplication does not care about order — $3 \\times (-5)$ and $(-5) \\times 3$ both give $-15$. Division does:",
        "",
        "$$",
        "(-12) \\div 4 = -3 \\qquad 4 \\div (-12) \\text{ is not } -3",
        "$$",
        "",
        "So keep the numbers in the order the question gives them.",
        "",
        "### Worked example",
        "",
        "A well's water level drops 4 cm every day. Altogether it has dropped 52 cm. For how many days has this been going on?",
        "",
        "A drop of 52 cm is $-52$, and each day is $-4$:",
        "",
        "$$",
        "(-52) \\div (-4) = 13",
        "$$",
        "",
        "13 days. The answer is positive, and it should be — a count of days cannot be negative.",
      ].join("\n"),
      // Nothing new to learn, and the lesson says so first — the whole risk here
      // is a learner treating division as a fresh set of rules to memorise.
      steps: [
        {
          kind: "see",
          md: "Division undoes multiplication, so it borrows the same sign rules.",
          viz: { kind: "tokenRow", positive: 0, negative: 12, groupsOf: 4, label: "(−12) ÷ 3 = −4" },
        },
        {
          kind: "reveal",
          md: "$(-24) \\div 6$?",
          answer: "$-4$. Different signs, so the answer is negative.",
        },
        {
          kind: "tap",
          md: "And $(-36) \\div (-9)$?",
          options: [{ label: "$4$" }, { label: "$-4$" }],
          answer: 0,
          why: "Same signs give a positive. Check it: $4 \\times (-9) = -36$.",
        },
        {
          kind: "see",
          md: "You can always check a division by multiplying back.",
        },
        {
          kind: "reveal",
          md: "Multiplying does not care about order. Does dividing?",
          answer: "It does. $(-12) \\div 4 = -3$, but $4 \\div (-12)$ is not $-3$. Keep the given order.",
        },
        {
          kind: "see",
          md: "A well's water drops 4 cm every day. Altogether it has dropped 52 cm.",
        },
        {
          kind: "reveal",
          md: "For how many days has this been going on?",
          answer: "$(-52) \\div (-4) = 13$ days. Positive, as it must be — a count of days cannot be negative.",
        },
        {
          kind: "tap",
          md: "$(-45) \\div 5$?",
          options: [{ label: "$-9$" }, { label: "$9$" }],
          answer: 0,
          why: "Different signs, so negative. Then $45 \\div 5 = 9$.",
        },
      ],
    },
  ],

  questions: [
    // ── PLACE — the answer is a POSITION, which is how the line is taught ─────
    {
      slug: "c7-nl-d1-q4",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "Tap the line where $-3$ sits.",
      answer_value: "-3",
      input: { kind: "place", from: -5, to: 5, step: 1 },
      solution_md: [
        "Negative numbers live to the **left** of zero, and they count outwards the same way positive ones do.",
        "",
        "From 0, go left three steps: $-1$, $-2$, $-3$.",
        "",
        "It sits the same distance from zero as $3$ does — just on the other side.",
      ].join("\n"),
    },
    {
      slug: "c7-nl-d2-q3",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "Tap the number that is $3$ **less** than $-1$.",
      answer_value: "-4",
      input: { kind: "place", from: -8, to: 4, step: 1 },
      solution_md: [
        "**Less** means move **left**, wherever you are starting from.",
        "",
        "Start at $-1$ and take three steps left: $-2$, $-3$, $-4$.",
        "",
        "$$\n-1 - 3 = -4\n$$",
        "",
        "Going left from a negative number takes you further from zero, so the answer is *more* negative — not closer to it.",
      ].join("\n"),
    },
    // ─────────────────────────────────────────────────────────────────────────
    // PICTORIAL RECOGNITION (D18 slice 5.2) — read the notation, find the picture.
    //
    // Class 7's two shapes carry different ideas and are not interchangeable.
    // Adding is a WALK, so it belongs on the line: the answer is where you land.
    // Multiplying is COUNTING LOTS, so it belongs on chips: repeated jumps along
    // a line just look like one long jump, which teaches nothing.
    //
    // Diagrams are never translated (D18 §6) — only stems and solutions have Hindi.
    // ─────────────────────────────────────────────────────────────────────────
    {
      slug: "c7-add-d1-q3",
      concept_slug: "adding-subtracting-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "Start at $-5$ and move $3$ to the right.\n\nWhich picture shows where you land?",
      answer_value: "-2",
      input: {
        kind: "choiceViz",
        options: [
          {
            value: "-2",
            viz: { kind: "numberLine", from: -8, to: 4, step: 1,
                   jumps: [{ from: -5, to: -2 }], marks: [{ at: -2, tone: "correct" }] },
          },
          {
            // Moved LEFT instead of right — treating "+3" as "3 more of the same
            // direction you already are". The commonest first error on the line.
            value: "-8",
            viz: { kind: "numberLine", from: -8, to: 4, step: 1,
                   jumps: [{ from: -5, to: -8 }], marks: [{ at: -8 }] },
          },
          {
            // Dropped the sign and started from +5.
            value: "8",
            viz: { kind: "numberLine", from: -8, to: 9, step: 1,
                   jumps: [{ from: 5, to: 8 }], marks: [{ at: 8 }] },
          },
        ],
      },
      solution_md: [
        "Moving **right** always makes a number bigger, whether you start on the minus side or not.",
        "",
        "From $-5$, three steps right lands on $-4$, $-3$, $-2$.",
        "",
        "$$\n-5 + 3 = -2\n$$",
        "",
        "It is still a negative number — you did not travel far enough to reach zero. That is the whole picture.",
      ].join("\n"),
    },
    {
      slug: "c7-mul-d1-q3",
      concept_slug: "multiplying-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "Which picture shows $3 \\times (-2)$?",
      answer_value: "-6",
      input: {
        kind: "choiceViz",
        options: [
          // Three lots of "two owed" — six negative chips.
          { value: "-6", viz: { kind: "tokenRow", positive: 0, negative: 6, groupsOf: 2 } },
          // Counted the 3 and the 2 instead of taking 3 lots of 2.
          { value: "-5", viz: { kind: "tokenRow", positive: 0, negative: 5 } },
          // Lost the sign — the error the whole chapter is about.
          { value: "6", viz: { kind: "tokenRow", positive: 6, negative: 0, groupsOf: 2 } },
        ],
      },
      solution_md: [
        "$3 \\times (-2)$ means **three lots of** $-2$ — three groups, each of them a debt of 2.",
        "",
        "$$\n(-2) + (-2) + (-2) = -6\n$$",
        "",
        "Three groups of two chips is six chips, and every one of them is owed. So the answer is negative.",
      ].join("\n"),
    },
    // ── integers-number-line ────────────────────────────────────────────────
    {
      slug: "c7-nl-d1-q1",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 1,
      answer_type: "mcq",
      stem_md: "Which is **smaller**, $-5$ or $-2$?",
      choices: [
        { id: "a", label: "$-5$" },
        { id: "b", label: "$-2$, because 2 is smaller than 5" },
        { id: "c", label: "They are equal in size" },
        { id: "d", label: "You cannot compare negative numbers" },
      ],
      answer_value: "a",
      solution_md: [
        "On the number line, $-5$ sits further to the **left** than $-2$, and further left means smaller.",
        "",
        "$$",
        "-5 < -2",
        "$$",
        "",
        "Option (b) is the trap almost everyone falls into once. Think about money: owing ₹5 leaves you worse off than owing ₹2.",
      ].join("\n"),
    },
    {
      slug: "c7-nl-d1-q2",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "What is the **opposite** of $-9$?",
      answer_value: "9",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "9"] },
      solution_md: [
        "The opposite of an integer is the same distance from 0, on the other side.",
        "",
        "$-9$ is 9 steps to the left of 0, so its opposite is 9 steps to the **right** of 0 — that is $9$.",
        "",
        "A useful check: a number plus its opposite is always 0, and $(-9) + 9 = 0$.",
      ].join("\n"),
    },
    {
      slug: "c7-nl-d2-q1",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "Which integer is **5 units to the left** of $-2$ on the number line?",
      answer_value: "-7",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "5", "7"] },
      solution_md: [
        "Moving left means going down. Start at $-2$ and count five steps left:",
        "",
        "$$",
        "-3, -4, -5, -6, -7",
        "$$",
        "",
        "You land on $-7$. In symbols, moving left is subtracting: $(-2) - 5 = -7$.",
      ].join("\n"),
    },
    {
      slug: "c7-nl-d2-q2",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 2,
      answer_type: "mcq",
      stem_md: "Which list is arranged from **smallest to largest**?",
      choices: [
        { id: "a", label: "$-7,\\ -2,\\ 0,\\ 3$" },
        { id: "b", label: "$0,\\ -2,\\ 3,\\ -7$" },
        { id: "c", label: "$-2,\\ -7,\\ 0,\\ 3$" }, // ordered the negatives by size
        { id: "d", label: "$3,\\ 0,\\ -2,\\ -7$" }, // largest to smallest
      ],
      answer_value: "a",
      solution_md: [
        "Read them off the number line from left to right:",
        "",
        "$$",
        "-7 < -2 < 0 < 3",
        "$$",
        "",
        "Option (c) puts $-2$ before $-7$, which is the usual slip — among negatives, the one with the **bigger** digits is the **smaller** number.",
      ].join("\n"),
    },
    {
      slug: "c7-nl-d3-q1",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: "How many integers lie **strictly between** $-4$ and $3$?",
      answer_value: "6",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "6"] },
      solution_md: [
        "*Strictly between* means $-4$ and $3$ themselves do not count. List what is left:",
        "",
        "$$",
        "-3, -2, -1, 0, 1, 2",
        "$$",
        "",
        "That is **6** integers. Do not forget 0 — it is an integer, and it is the one most often missed.",
      ].join("\n"),
    },
    {
      slug: "c7-nl-d3-q2",
      concept_slug: "integers-number-line",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md:
        "A number and its opposite are **18 units apart** on the number line.\n\nWhat is the positive one of the two?",
      answer_value: "9",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "8", "9"] },
      solution_md: [
        "A number and its opposite sit the same distance from 0, one on each side.",
        "",
        "So the gap between them is **twice** that distance:",
        "",
        "$$",
        "2 \\times \\text{distance} = 18",
        "$$",
        "",
        "The distance from 0 is $18 \\div 2 = 9$, so the two numbers are $9$ and $-9$. The positive one is **9**.",
      ].join("\n"),
    },

    // ── adding-subtracting-integers ─────────────────────────────────────────
    {
      slug: "c7-add-d1-q1",
      concept_slug: "adding-subtracting-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n(-7) + 3\n$$",
      answer_value: "-4",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "7"] },
      solution_md: [
        "Start at $-7$ and move **3 to the right**.",
        "",
        "$$",
        "-7 \\to -6 \\to -5 \\to -4",
        "$$",
        "",
        "The signs are different, so subtract the sizes ($7 - 3 = 4$) and keep the sign of the bigger one, which is negative.",
        "",
        "$$",
        "(-7) + 3 = -4",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-add-d1-q2",
      concept_slug: "adding-subtracting-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n5 - 8\n$$",
      answer_value: "-3",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "5", "8"] },
      solution_md: [
        "Subtracting 8 means moving 8 steps to the **left** from 5. You pass 0 and keep going:",
        "",
        "$$",
        "5 - 8 = 5 + (-8) = -3",
        "$$",
        "",
        "A smaller number minus a bigger one always lands below zero.",
      ].join("\n"),
    },
    {
      slug: "c7-add-d2-q1",
      concept_slug: "adding-subtracting-integers",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n(-6) - (-9)\n$$",
      answer_value: "3",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "6", "9"] },
      solution_md: [
        "To subtract an integer, **add its opposite**. The opposite of $-9$ is $9$:",
        "",
        "$$",
        "(-6) - (-9) = (-6) + 9 = 3",
        "$$",
        "",
        "Taking away a debt leaves you better off, which is why the answer comes out positive.",
      ].join("\n"),
    },
    {
      slug: "c7-add-d2-q2",
      concept_slug: "adding-subtracting-integers",
      kind: "practice",
      difficulty: 2,
      answer_type: "mcq",
      stem_md:
        "The temperature in Shimla was $-3$°C. Overnight it fell by another 7 degrees.\n\nWhat is the temperature now?",
      choices: [
        { id: "a", label: "$-10$°C" },
        { id: "b", label: "$4$°C" }, // subtracted the wrong way round
        { id: "c", label: "$10$°C" }, // lost the sign
        { id: "d", label: "$-4$°C" }, // 7 - 3
      ],
      answer_value: "a",
      solution_md: [
        "*Fell* means move **left** on the number line — it is already cold, and it got colder.",
        "",
        "$$",
        "(-3) - 7 = -10",
        "$$",
        "",
        "So it is $-10$°C. If an answer came out warmer than $-3$°C, the move went the wrong way.",
      ].join("\n"),
    },
    {
      slug: "c7-add-d3-q1",
      concept_slug: "adding-subtracting-integers",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: "$$\n(-12) + 5 - (-7)\n$$",
      answer_value: "0",
      input: { kind: "tiles", bank: ["-", "0", "1", "2", "5", "7"] },
      solution_md: [
        "Work left to right, and turn the subtraction into adding the opposite.",
        "",
        "$$",
        "(-12) + 5 = -7",
        "$$",
        "",
        "$$",
        "(-7) - (-7) = (-7) + 7 = 0",
        "$$",
        "",
        "A number plus its opposite is always 0.",
      ].join("\n"),
    },
    {
      slug: "c7-add-d3-q2",
      concept_slug: "adding-subtracting-integers",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: [
        "Ravi owes ₹250. He repays ₹90, then borrows ₹40 more.",
        "",
        "Which integer represents his balance now?",
      ].join("\n"),
      answer_value: "-200",
      input: { kind: "tiles", bank: ["-", "0", "1", "2", "3", "4"] },
      solution_md: [
        "Money owed is negative, repaying moves **up**, borrowing moves **down**.",
        "",
        "$$",
        "-250 + 90 = -160",
        "$$",
        "",
        "$$",
        "-160 - 40 = -200",
        "$$",
        "",
        "So his balance is $-200$ — he owes ₹200.",
      ].join("\n"),
    },

    // ── multiplying-integers ────────────────────────────────────────────────
    {
      slug: "c7-mul-d1-q1",
      concept_slug: "multiplying-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n(-4) \\times 3\n$$",
      answer_value: "-12",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "5"] },
      solution_md: [
        "Multiplication is repeated addition:",
        "",
        "$$",
        "(-4) + (-4) + (-4) = -12",
        "$$",
        "",
        "Different signs give a negative answer. Three lots of a ₹4 debt is a ₹12 debt.",
      ].join("\n"),
    },
    {
      slug: "c7-mul-d1-q2",
      concept_slug: "multiplying-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "mcq",
      stem_md: "What is the **sign** of $(-5) \\times (-6)$?",
      choices: [
        { id: "a", label: "Positive" },
        { id: "b", label: "Negative, because both numbers are negative" },
        { id: "c", label: "Zero" },
        { id: "d", label: "It depends on which number comes first" },
      ],
      answer_value: "a",
      solution_md: [
        "**Same signs give a positive.** Two negatives multiplied together give a positive answer:",
        "",
        "$$",
        "(-5) \\times (-6) = 30",
        "$$",
        "",
        "Option (d) is worth ruling out too — multiplication gives the same answer whichever order you write it in.",
      ].join("\n"),
    },
    {
      slug: "c7-mul-d2-q1",
      concept_slug: "multiplying-integers",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n(-7) \\times (-8)\n$$",
      answer_value: "56",
      input: { kind: "tiles", bank: ["-", "1", "5", "6", "7", "8"] },
      solution_md: [
        "Same signs, so the answer is **positive**. Now multiply the sizes:",
        "",
        "$$",
        "7 \\times 8 = 56",
        "$$",
        "",
        "$$",
        "(-7) \\times (-8) = 56",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-mul-d2-q2",
      concept_slug: "multiplying-integers",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n(-2) \\times 3 \\times (-5)\n$$",
      answer_value: "30",
      input: { kind: "tiles", bank: ["-", "0", "1", "2", "3", "5"] },
      solution_md: [
        "Count the minus signs first: there are **two**, an even number, so the answer is positive.",
        "",
        "Now multiply the sizes:",
        "",
        "$$",
        "2 \\times 3 \\times 5 = 30",
        "$$",
        "",
        "$$",
        "(-2) \\times 3 \\times (-5) = 30",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-mul-d3-q1",
      concept_slug: "multiplying-integers",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: "$$\n(-1) \\times (-1) \\times (-1) \\times (-1) \\times (-1)\n$$",
      answer_value: "-1",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "5"] },
      solution_md: [
        "Do not multiply one step at a time — **count the minus signs**. There are five, an **odd** number, so the answer is negative.",
        "",
        "The sizes are all 1, so the size of the answer is 1.",
        "",
        "$$",
        "(-1) \\times (-1) \\times (-1) \\times (-1) \\times (-1) = -1",
        "$$",
        "",
        "Even number of negatives → positive. Odd number → negative.",
      ].join("\n"),
    },
    {
      slug: "c7-mul-d3-q2",
      concept_slug: "multiplying-integers",
      kind: "practice",
      difficulty: 3,
      answer_type: "mcq",
      stem_md: [
        "A diver goes down 3 metres every minute, starting from the surface.",
        "",
        "Where is she after 7 minutes?",
      ].join("\n"),
      choices: [
        { id: "a", label: "$-21$ m" },
        { id: "b", label: "$21$ m" }, // lost the sign
        { id: "c", label: "$-10$ m" }, // added instead of multiplied
        { id: "d", label: "$-4$ m" }, // subtracted instead of multiplied
      ],
      answer_value: "a",
      solution_md: [
        "Going down 3 m is $-3$, and it happens 7 times:",
        "",
        "$$",
        "(-3) \\times 7 = -21",
        "$$",
        "",
        "She is 21 m **below** the surface, which we write as $-21$ m. The minus sign is not decoration — it is the difference between 21 m under water and 21 m in the air.",
      ].join("\n"),
    },

    // ── dividing-integers ───────────────────────────────────────────────────
    {
      slug: "c7-div-d1-q1",
      concept_slug: "dividing-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n(-24) \\div 6\n$$",
      answer_value: "-4",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "6"] },
      solution_md: [
        "Different signs give a **negative** answer. Divide the sizes: $24 \\div 6 = 4$.",
        "",
        "$$",
        "(-24) \\div 6 = -4",
        "$$",
        "",
        "Check by multiplying back: $(-4) \\times 6 = -24 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c7-div-d1-q2",
      concept_slug: "dividing-integers",
      kind: "practice",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n(-36) \\div (-9)\n$$",
      answer_value: "4",
      input: { kind: "tiles", bank: ["-", "1", "3", "4", "6", "9"] },
      solution_md: [
        "Same signs give a **positive** answer. Divide the sizes: $36 \\div 9 = 4$.",
        "",
        "$$",
        "(-36) \\div (-9) = 4",
        "$$",
        "",
        "Check: $4 \\times (-9) = -36 \\ \\checkmark$",
      ].join("\n"),
    },
    {
      slug: "c7-div-d2-q1",
      concept_slug: "dividing-integers",
      kind: "practice",
      difficulty: 2,
      answer_type: "mcq",
      stem_md: "Which of these is **not** equal to $-5$?",
      choices: [
        { id: "a", label: "$(-25) \\div (-5)$" },
        { id: "b", label: "$25 \\div (-5)$" },
        { id: "c", label: "$(-25) \\div 5$" },
        { id: "d", label: "$(-5) \\times 1$" },
      ],
      answer_value: "a",
      solution_md: [
        "Check each one:",
        "",
        "- $(-25) \\div (-5) = 5$ — same signs, so **positive**. This is the odd one out.",
        "- $25 \\div (-5) = -5$",
        "- $(-25) \\div 5 = -5$",
        "- $(-5) \\times 1 = -5$",
        "",
        "So the answer is (a). Same signs give a positive — even when both numbers look negative.",
      ].join("\n"),
    },
    {
      slug: "c7-div-d2-q2",
      concept_slug: "dividing-integers",
      kind: "practice",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n(-48) \\div (-4) \\div (-3)\n$$",
      answer_value: "-4",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "8"] },
      solution_md: [
        "Work **left to right** — division does not let you reorder.",
        "",
        "$$",
        "(-48) \\div (-4) = 12",
        "$$",
        "",
        "$$",
        "12 \\div (-3) = -4",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-div-d3-q1",
      concept_slug: "dividing-integers",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md: [
        "A well's water level drops 4 cm every day. Altogether it has dropped 52 cm.",
        "",
        "For how many days has this been happening?",
      ].join("\n"),
      answer_value: "13",
      input: { kind: "tiles", bank: ["-", "1", "2", "3", "4", "5"] },
      solution_md: [
        "A drop is negative. The total drop is $-52$ and each day is $-4$:",
        "",
        "$$",
        "(-52) \\div (-4) = 13",
        "$$",
        "",
        "13 days. Same signs give a positive answer — and that is exactly right here, because a number of days cannot be negative.",
      ].join("\n"),
    },
    {
      slug: "c7-div-d3-q2",
      concept_slug: "dividing-integers",
      kind: "practice",
      difficulty: 3,
      answer_type: "integer",
      stem_md:
        "Which integer, when divided by $-7$, gives $9$?",
      answer_value: "-63",
      input: { kind: "tiles", bank: ["-", "1", "3", "6", "7", "9"] },
      solution_md: [
        "This runs backwards, so undo the division by multiplying:",
        "",
        "$$",
        "9 \\times (-7) = -63",
        "$$",
        "",
        "Check it: $(-63) \\div (-7) = 9 \\ \\checkmark$",
      ].join("\n"),
    },

    // ── quiz ────────────────────────────────────────────────────────────────
    {
      slug: "c7-quiz-nl-1",
      concept_slug: "integers-number-line",
      kind: "quiz",
      difficulty: 1,
      answer_type: "mcq",
      stem_md: "Which is the **greatest** of these: $-20$, $-2$, $-11$?",
      choices: [
        { id: "a", label: "$-2$" },
        { id: "b", label: "$-20$" },
        { id: "c", label: "$-11$" },
        { id: "d", label: "They are all equal" },
      ],
      answer_value: "a",
      solution_md: [
        "All three are to the left of 0, and the greatest is the one **furthest right** — the one closest to zero.",
        "",
        "$$",
        "-20 < -11 < -2",
        "$$",
        "",
        "So $-2$ is the greatest.",
      ].join("\n"),
    },
    {
      slug: "c7-quiz-nl-2",
      concept_slug: "integers-number-line",
      kind: "quiz",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "Which integer is **4 units to the right** of $-9$?",
      answer_value: "-5",
      solution_md: [
        "Moving right means adding:",
        "",
        "$$",
        "(-9) + 4 = -5",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-quiz-add-1",
      concept_slug: "adding-subtracting-integers",
      kind: "quiz",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n(-15) + 20\n$$",
      answer_value: "5",
      solution_md: [
        "Different signs, so subtract the sizes and keep the sign of the bigger one. $20 - 15 = 5$, and 20 is positive.",
        "",
        "$$",
        "(-15) + 20 = 5",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-quiz-add-2",
      concept_slug: "adding-subtracting-integers",
      kind: "quiz",
      difficulty: 3,
      answer_type: "integer",
      stem_md: "$$\n8 - (-6) - 20\n$$",
      answer_value: "-6",
      solution_md: [
        "Subtracting $-6$ means adding 6:",
        "",
        "$$",
        "8 + 6 = 14",
        "$$",
        "",
        "$$",
        "14 - 20 = -6",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-quiz-mul-1",
      concept_slug: "multiplying-integers",
      kind: "quiz",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n(-9) \\times 4\n$$",
      answer_value: "-36",
      solution_md: [
        "Different signs give a negative answer, and $9 \\times 4 = 36$.",
        "",
        "$$",
        "(-9) \\times 4 = -36",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-quiz-mul-2",
      concept_slug: "multiplying-integers",
      kind: "quiz",
      difficulty: 2,
      answer_type: "integer",
      stem_md: "$$\n(-3) \\times (-4) \\times 2\n$$",
      answer_value: "24",
      solution_md: [
        "Two minus signs — an even number — so the answer is positive.",
        "",
        "$$",
        "3 \\times 4 \\times 2 = 24",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-quiz-div-1",
      concept_slug: "dividing-integers",
      kind: "quiz",
      difficulty: 1,
      answer_type: "integer",
      stem_md: "$$\n(-45) \\div 9\n$$",
      answer_value: "-5",
      solution_md: [
        "Different signs give a negative answer, and $45 \\div 9 = 5$.",
        "",
        "$$",
        "(-45) \\div 9 = -5",
        "$$",
      ].join("\n"),
    },
    {
      slug: "c7-quiz-div-2",
      concept_slug: "dividing-integers",
      kind: "quiz",
      difficulty: 3,
      answer_type: "integer",
      stem_md:
        "The product of two integers is $-72$. One of them is $-8$.\n\nWhat is the other?",
      answer_value: "9",
      solution_md: [
        "Undo the multiplication by dividing:",
        "",
        "$$",
        "(-72) \\div (-8) = 9",
        "$$",
        "",
        "Same signs give a positive answer. Check it: $(-8) \\times 9 = -72 \\ \\checkmark$",
      ].join("\n"),
    },
  ],
};
